# https://taskfile.dev
version: '3'

tasks:
  default:
    cmds:
      - task: fmt
      - task: test

  install:
    desc: "Installs dependencies and pre-commit"
    cmds:
      - mkdir -p __pypackages__
      - pdm install
      - pre-commit install

  fmt:
    desc: "Formats code using ruff and black"
    cmds:
     - ruff --fix .
     - black .

  test:
    desc: "Run tests"
    cmds:
     - pdm run pytest -v tests
